### ISSUE TITLE
Setting datacenter_id in knife.rb has no effect

### ISSUE THREAD

**Issue by jbuchhammer** [profitbricks/knife-profitbricks#8]
According to the documentation of knife-profitbricks 

> the data center ID can be added to the knife.rb which reduces the need to include the --datacenter-id parameter for each action within the data center.

Therefore I would expect that executing

`knife profitbricks server list`

will return a list of servers in a datacenter if I set it's ID by

`knife[:datacenter_id] = '9b43cffa-d348-40f8-88ca-e4d58da5a26e'`

in knife.rb.
Instead the call fails with the error message
`You must supply -D DATACENTER_ID!`

When I change the call to

`knife profitbricks server list -D '9b43cffa-d348-40f8-88ca-e4d58da5a26e'`

the servers within the datacenter are displayed.

That my knife.rb is used, is confirmed by the fact that my profitbricks_username is also set in knife.rb

**Comment by edevenport** [comment]
@jbuchhammer This has been resolved in #10 and v1.2.1 has been released. The `--datacenter-id` parameter was explicitly set to required. Once that was removed, the ID is now properly read from the knife.rb.
